export const GET_ITEMS_LIST = 'items/GET_ITEMS_LIST'
export const START_FETCHING = 'items/START_FETCHING'
export const INIT_STORIES = 'items/INIT_STORIES'
export const INIT_STORIES_DETAILS = 'items/INIT_STORIES_DETAILS'
export const ERROR_GENERATED = 'items/ERROR_GENERATED'
